DROP TABLE IF EXISTS users, requests, items, bookings, comments, requests;

CREATE TABLE IF NOT EXISTS users (id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY, name varchar(255) NOT NULL, email varchar(512) NOT NULL, CONSTRAINT UQ_USER_EMAIL UNIQUE (email));

CREATE TABLE IF NOT EXISTS requests (id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY, description VARCHAR NOT NULL, requester_id bigint REFERENCES users(id), created TIMESTAMP WITHOUT TIME ZONE NOT NULL);

CREATE TABLE IF NOT EXISTS items (id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY, name varchar(255) NOT NULL, description varchar(1000) NOT NULL, available BOOLEAN, owner_id BIGINT REFERENCES users(id), request_id BIGINT REFERENCES requests(id), CONSTRAINT UQ_ITEM_NAME UNIQUE (name));

CREATE TABLE IF NOT EXISTS bookings (id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY, start_time TIMESTAMP WITHOUT TIME ZONE NOT NULL, end_time TIMESTAMP WITHOUT TIME ZONE NOT NULL, item_id BIGINT REFERENCES items(id), booker_id BIGINT REFERENCES users(id), status varchar(50));

CREATE TABLE IF NOT EXISTS comments (id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY, text VARCHAR NOT NULL, item_id BIGINT REFERENCES items(id), author_id BIGINT REFERENCES users(id) ON DELETE CASCADE NOT NULL, created TIMESTAMP WITHOUT TIME ZONE NOT NULL);
